wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1654053756
    t:
      1:
      - 55
      2:
      - 55
      4: 3.8.8
      5: 0.12.16
      8:
      - 5
